export const uiCopy = {
  nav: {
    add: "Hinzufügen",
    today: "Heute",
    library: "Bibliothek",
    profile: "Profil",
  },
  auth: {
    heading: "Kalorien schnell und klar im Blick",
    startDemo: "Lokale Demo starten",
    continueGoogle: "Mit Google fortfahren",
    tryDemo: "Demo testen",
  },
  mealCard: {
    favorite: "Favorit",
    favorited: "Favorisiert",
    edit: "Bearbeiten",
    delete: "Löschen",
    quantity: "Menge",
    assessment: "Einschätzung",
    assumptions: "Annahmen",
    relog: "Erneut eintragen",
    protein: "Protein",
    carbsShort: "Kohlenh.",
    fat: "Fett",
    kcal: "KCAL",
  },
  today: {
    heading: "Heute",
    entries: "Einträge",
    empty: "Noch keine Einträge für heute.",
    previousDay: "Vorheriger Tag",
    nextDay: "Nächster Tag",
    averages: "Ø",
    weeklyAverage: "7 Tage",
    monthlyAverage: "30 Tage",
    openStats: "Statistik öffnen",
    statsTitle: "Statistik",
    chartLabel: "Kalorienverlauf der letzten 30 Tage",
    todayMarker: "Heute",
    addFromLibrary: "Schnell hinzufügen",
  },
  library: {
    heading: "Bibliothek",
    searchPlaceholder: "Einträge suchen",
    emptyFavorites: "Noch keine Favoriten.",
    usedCount: (count: number) => `${count}x genutzt`,
  },
  summary: {
    eyebrow: "Tagesübersicht",
    title: "Heute im Blick",
    targetPrefix: "Tagesziel:",
    targetUnavailable: "Ziel nicht verfügbar",
    consumed: "Verbraucht",
    completeProfile: "Profil ergänzen",
    missingGoal: "Ziel fehlt",
    noTarget: "Kein Ziel",
  },
  profile: {
    heading: "Profil",
    intro: "Persönliche Angaben, Darstellung und App-Updates an einem Ort.",
    account: "Konto",
    dailyTarget: "Tagesziel",
    incomplete: "Unvollständig",
    calculatedFromProfile: "Aus deinem Profil berechnet",
    completeProfileHint: "Ergänze Alter, Geschlecht, Größe, Gewicht und Aktivität.",
    app: "App",
    updates: "Updates",
    updateHint: "Prüfe manuell, ob eine neue PWA-Version bereitsteht.",
    updateCurrent: "App ist aktuell",
    updateAvailable: "Update verfügbar",
    updateReloadHint: "Lade die App neu, um die aktuelle Version zu aktivieren.",
    updateManualHint: "Die App prüft nur auf Wunsch.",
    checkUpdates: "Auf Updates prüfen",
    checkingUpdates: "Prüfe...",
    reload: "Neu laden",
    settings: "Einstellungen",
    appearance: "Darstellung",
    units: "Einheiten",
    metric: "Metrisch",
    imperial: "US",
    age: "Alter",
    sex: "Geschlecht",
    select: "Auswählen",
    female: "Weiblich",
    male: "Männlich",
    height: "Größe",
    weight: "Gewicht",
    activity: "Aktivität",
    save: "Profil speichern",
    saved: "Profil gespeichert.",
    signOut: "Abmelden",
    loadingSaved: "Deine gespeicherten Angaben werden synchronisiert...",
    loading: "Profil wird geladen.",
    missing: "Dein gespeichertes Profil konnte noch nicht geladen werden.",
    syncLag: "Die Synchronisierung läuft noch. Bitte versuche es gleich erneut.",
  },
  logFlow: {
    addEntry: "Eintrag hinzufügen",
    editEntry: "Eintrag bearbeiten",
    reviewEdit: "Bearbeitung prüfen",
    manualEdit: "Gericht bearbeiten",
    estimate: "Schätzung",
    estimateAction: "Schätzen",
    estimating: "Schätze...",
    save: "Speichern",
    saving: "Speichere...",
    update: "Aktualisieren",
    updating: "Aktualisiere...",
    back: "Zurück",
    assumptions: "Annahmen",
    takePhoto: "Foto aufnehmen",
    chooseLibrary: "Aus Galerie wählen",
    addPhoto: "Foto hinzufügen",
    entryPlaceholder: "Schreibe oder diktiere, was du gegessen hast",
    emptyEntry: "Füge ein Foto hinzu oder schreibe, was du gegessen hast.",
    genericError: "Wir konnten den Eintrag nicht auswerten. Beschreibe das Gericht klarer oder nutze ein deutlicheres Foto.",
    mealPreview: "Vorschau der Mahlzeit",
    mealTitle: "Name",
    mealSummary: "Notiz",
    itemName: "Item",
    itemPortion: "Portion",
    itemCalories: "kcal",
    itemProtein: "Protein",
    itemCarbs: "Kohlenh.",
    itemFat: "Fett",
    itemFiber: "Ballastst.",
    addItem: "Item hinzufügen",
    removeItem: "Item entfernen",
    manualEditError: "Prüfe Titel, Zutaten und Nährwerte. Mindestens eine Zutat braucht Name, Portion und kcal.",
  },
} as const;
