export const uiCopy = {
  nav: {
    add: "Hinzufuegen",
    today: "Heute",
    library: "Bibliothek",
    profile: "Profil",
  },
  auth: {
    heading: "Kalorien schnell und klar im Blick",
    startDemo: "Lokale Demo starten",
    continueGoogle: "Mit Google fortfahren",
    tryDemo: "Demo testen",
  },
  mealCard: {
    favorite: "Favorit",
    favorited: "Favorisiert",
    edit: "Bearbeiten",
    delete: "Loeschen",
    quantity: "Menge",
    assessment: "Einschaetzung",
    assumptions: "Annahmen",
    relog: "Erneut eintragen",
    protein: "Protein",
    carbsShort: "Kohlenh.",
    fat: "Fett",
    kcal: "KCAL",
  },
  today: {
    heading: "Heute",
    empty: "Noch keine Eintraege fuer heute.",
  },
  library: {
    heading: "Bibliothek",
    subheading: "Durchsuche fruehere Eintraege und deine Favoriten.",
    searchPlaceholder: "Eintraege suchen",
    all: "Alle",
    favorites: "Favoriten",
    emptyFavorites: "Noch keine Favoriten.",
    usedCount: (count: number) => `${count}x genutzt`,
  },
  summary: {
    eyebrow: "Tagesuebersicht",
    title: "Heute im Blick",
    targetPrefix: "Tagesziel:",
    targetUnavailable: "Ziel nicht verfuegbar",
    budget: "Budget",
    consumed: "Verbraucht",
    completeProfile: "Profil ergaenzen",
    missingGoal: "Ziel fehlt",
    noTarget: "Kein Ziel",
  },
  profile: {
    heading: "Profil",
    intro: "Persoenliche Angaben, Darstellung und App-Updates an einem Ort.",
    account: "Konto",
    dailyTarget: "Tagesziel",
    incomplete: "Unvollstaendig",
    calculatedFromProfile: "Aus deinem Profil berechnet",
    completeProfileHint: "Ergaenze Alter, Geschlecht, Groesse, Gewicht und Aktivitaet.",
    app: "App",
    updates: "Updates",
    updateHint: "Pruefe manuell, ob eine neue PWA-Version bereitsteht.",
    updateCurrent: "App ist aktuell",
    updateAvailable: "Update verfuegbar",
    updateReloadHint: "Lade die App neu, um die aktuelle Version zu aktivieren.",
    updateManualHint: "Die App prueft nur auf Wunsch.",
    checkUpdates: "Auf Updates pruefen",
    checkingUpdates: "Pruefe...",
    reload: "Neu laden",
    settings: "Einstellungen",
    appearance: "Darstellung",
    units: "Einheiten",
    metric: "Metrisch",
    imperial: "US",
    age: "Alter",
    sex: "Geschlecht",
    select: "Auswaehlen",
    female: "Weiblich",
    male: "Maennlich",
    height: "Groesse",
    weight: "Gewicht",
    activity: "Aktivitaet",
    save: "Profil speichern",
    saved: "Profil gespeichert.",
    signOut: "Abmelden",
    loadingSaved: "Deine gespeicherten Angaben werden synchronisiert...",
    loading: "Profil wird geladen.",
    missing: "Dein gespeichertes Profil konnte noch nicht geladen werden.",
    syncLag: "Die Synchronisierung laeuft noch. Bitte versuche es gleich erneut.",
  },
  logFlow: {
    addEntry: "Eintrag hinzufuegen",
    editEntry: "Eintrag bearbeiten",
    reviewEdit: "Bearbeitung pruefen",
    estimate: "Schaetzung",
    estimateAction: "Schaetzen",
    estimating: "Schaetze...",
    refine: "Verfeinern",
    save: "Speichern",
    saving: "Speichere...",
    update: "Aktualisieren",
    updating: "Aktualisiere...",
    back: "Zurueck",
    assumptions: "Annahmen",
    takePhoto: "Foto aufnehmen",
    chooseLibrary: "Aus Galerie waehlen",
    addPhoto: "Foto hinzufuegen",
    entryPlaceholder: "Schreibe oder diktiere, was du gegessen hast",
    emptyEntry: "Fuege ein Foto hinzu oder schreibe, was du gegessen hast.",
    genericError: "Wir konnten den Eintrag nicht auswerten. Beschreibe das Gericht klarer oder nutze ein deutlicheres Foto.",
    mealPreview: "Vorschau der Mahlzeit",
  },
} as const;
